window.MCCDocContent = {
  "../docs/README.md": [
    "# Documentation Index",
    "",
    "This folder is the project documentation home for Mac Control Center.",
    "",
    "## Core Docs",
    "",
    "- `PROJECT_OVERVIEW.md`: Product summary, repo layout, and current scope.",
    "- `PROJECT_AUDIT.md`: Current-state audit and recommended next steps.",
    "- `APP_ARCHITECTURE.md`: High-level code architecture and runtime flow.",
    "- `ACTION_SYSTEM.md`: How actions are modeled, persisted, and executed.",
    "- `PERSISTENCE_AND_STATE.md`: What data lives where and how it survives restarts.",
    "- `LOCAL_PROJECT_SYSTEM.md`: How the local tracker, docs hub, and online sync model should work.",
    "- `RELEASE_AND_DEPLOYMENT.md`: Current release process and future packaging/CI plan.",
    "- `UI_AND_UX_GUIDELINES.md`: Native macOS design and interaction rules for this app.",
    "",
    "## Root-Level Reference Files",
    "",
    "- `../README.md`: Quick start and repo-level overview.",
    "- `../BEHAVIORS.md`: User-visible behavior log.",
    "- `../SECURITY.md`: Public repo and secrets guidance.",
    "",
    "## Maintenance Rule",
    "",
    "When product behavior changes, update the architecture or behavior docs in the same pass. When project-management workflow changes, update `LOCAL_PROJECT_SYSTEM.md` and the TaskTracker pages together."
  ].join("\n"),
  "../docs/PROJECT_OVERVIEW.md": [
    "# Project Overview",
    "",
    "## What This App Is",
    "",
    "Mac Control Center is a native macOS utility that gives the user a compact control hub for launching apps, running shell commands, and switching between multiple window modes.",
    "",
    "## Current Capabilities",
    "",
    "- Menu bar status item with a quick access menu",
    "- Main Dock window for managing actions",
    "- Expanded, Mini, and Dot display modes",
    "- Inline settings and inline action creation",
    "- Editable action list with reorder support",
    "- Local persistence for action configuration and window preferences",
    "- Quick-launch dock for a few frequently used apps",
    "",
    "## Repo Layout",
    "",
    "- `Sources/MacControlCenter/`: Swift source",
    "- `Resources/`: app icon and bundle assets",
    "- `build.sh`: local build and optional install script",
    "- `TaskTracker/`: local-first task tracker and documentation hub",
    "- `docs/`: markdown documentation for product, architecture, persistence, release, and workflow",
    "- `BEHAVIORS.md`: compact behavior log for user-visible interactions",
    "",
    "## Current Constraints",
    "",
    "- No automated tests yet",
    "- No packaged release workflow yet",
    "- No GitHub Actions CI/CD yet",
    "- Launch-at-login currently uses AppleScript login items",
    "- TaskTracker is local-first and browser-persistent, not automatically synced online"
  ].join("\n"),
  "../docs/PROJECT_AUDIT.md": [
    "# Project Audit",
    "",
    "Audit date: 2026-03-30",
    "",
    "## Current Strengths",
    "",
    "- The app is already native, lightweight, and buildable with a single script.",
    "- Configuration is separated from code through `ConfigManager`.",
    "- Action execution is isolated in `ActivityHandler`.",
    "- The window system already supports multiple usage modes with clear keyboard shortcuts.",
    "- The repository now has a local-first documentation and task-tracking structure.",
    "",
    "## Gaps Worth Addressing Next",
    "",
    "### Product",
    "",
    "- Quick-launch dock entries are hardcoded instead of user-configurable.",
    "- Action shortcut conflicts are not validated.",
    "- Action failures rely mostly on notifications rather than richer in-app feedback.",
    "- Import/export and backup for action config are not exposed in the UI.",
    "",
    "### Platform / Reliability",
    "",
    "- There is no automated build verification or test coverage.",
    "- Launch-at-login relies on AppleScript and may be brittle across macOS changes.",
    "- Shell action execution has limited safety guidance and no trust model.",
    "",
    "### Release / Operations",
    "",
    "- There is no GitHub Actions pipeline for build, package, or release.",
    "- There is no `.dmg` or `.zip` release artifact flow yet.",
    "- The local tracker does not automatically sync to any online system."
  ].join("\n"),
  "../docs/APP_ARCHITECTURE.md": [
    "# App Architecture",
    "",
    "## Runtime Entry Point",
    "",
    "`Sources/MacControlCenter/main.swift` starts the app, creates the status-item menu, opens the main window, and keeps the menu synchronized with configuration changes.",
    "",
    "## Main Components",
    "",
    "### `AppDelegate`",
    "",
    "- Creates the menu bar status item",
    "- Builds the status menu from saved actions",
    "- Opens and restores the main window",
    "- Rebuilds the menu when configuration changes",
    "",
    "### `ConfigManager`",
    "",
    "- Owns the action list",
    "- Loads and saves `config.json`",
    "- Normalizes action data before persistence",
    "- Publishes change notifications so the UI and menu stay in sync",
    "",
    "### `ActivityHandler`",
    "",
    "- Receives an `ActionButton`",
    "- Validates `actionType` and `actionTarget`",
    "- Launches applications with `NSWorkspace` or shell commands with `/bin/sh -c`",
    "- Shows notifications on invalid or failed actions"
  ].join("\n"),
  "../docs/ACTION_SYSTEM.md": [
    "# Action System",
    "",
    "## Data Model",
    "",
    "Each action is represented by `ActionButton`:",
    "",
    "- `id`: UUID generated locally",
    "- `name`: visible label",
    "- `key`: single-character shortcut",
    "- `actionType`: `app`, `shell`, or empty",
    "- `actionTarget`: application path or shell command",
    "",
    "## Storage Location",
    "",
    "`~/Library/Application Support/MacControlCenter/config.json`",
    "",
    "## Execution Rules",
    "",
    "- `app`: expects a valid `.app` path and launches with `NSWorkspace`",
    "- `shell`: runs through `/bin/sh -c`",
    "- empty or invalid action definitions trigger a user notification instead of a hard failure",
    "",
    "## Current Risks",
    "",
    "- Duplicate shortcuts are not prevented",
    "- There is no import/export UI for action backup",
    "- Shell commands can be powerful and should be treated as trusted local workflows",
    "- There is no richer execution log beyond notifications"
  ].join("\n"),
  "../docs/PERSISTENCE_AND_STATE.md": [
    "# Persistence and State",
    "",
    "This project has three different persistence layers, and they behave differently.",
    "",
    "## 1. App Configuration",
    "",
    "- Stored in `~/Library/Application Support/MacControlCenter/config.json`",
    "- Contains actions, keys, action types, and action targets",
    "- Local to the current macOS user account",
    "",
    "## 2. App Preferences",
    "",
    "- Stored in macOS `UserDefaults`",
    "- Contains view mode, always-on-top state, show-on-all-desktops state, opacity, and launch-at-login preference",
    "- Local to the current machine/user",
    "",
    "## 3. Local Task Tracker State",
    "",
    "- Repo seed data in `TaskTracker/project-data.js`",
    "- Browser-local working state in `localStorage`",
    "- Browser edits do not update the repo automatically",
    "- Browser edits do not update an online tracker automatically",
    "",
    "## Practical Answer",
    "",
    "If you add a new item in the local tracker UI, it will persist in that browser on that machine, but it will not automatically update across the board."
  ].join("\n"),
  "../docs/LOCAL_PROJECT_SYSTEM.md": [
    "# Local Project System",
    "",
    "## Goal",
    "",
    "Keep project management and documentation close to the codebase so AI agents and humans can update them in the same workspace.",
    "",
    "## Components",
    "",
    "### `TaskTracker/index.html`",
    "",
    "Local-first task board for backlog review, quick edits, export, and manual prioritization.",
    "",
    "### `TaskTracker/docs.html`",
    "",
    "Project docs hub linking the markdown docs and the repo-local skill files.",
    "",
    "### `TaskTracker/project-data.js`",
    "",
    "Repo-owned seed data for project metadata, seeded backlog items, docs index, and skill index.",
    "",
    "## AI-Recommended Tasks",
    "",
    "When an AI assistant adds a suggested task to the repo-owned backlog, mark it with `source: recommended` and `recommendedBy: Codex (GPT-5)`."
  ].join("\n"),
  "../docs/RELEASE_AND_DEPLOYMENT.md": [
    "# Release and Deployment",
    "",
    "## Current State",
    "",
    "The project supports local builds with `build.sh`.",
    "",
    "Current release process:",
    "",
    "1. Run `./build.sh`",
    "2. Open `build/MacControlCenter.app`",
    "3. Optionally install with `./build.sh --install`",
    "",
    "## What Does Not Exist Yet",
    "",
    "- GitHub Actions build pipeline",
    "- packaged `.dmg` or `.zip`",
    "- automated versioning",
    "- notarization / formal signing flow",
    "- GitHub Release publishing",
    "",
    "## Recommended Release Plan",
    "",
    "Start with build verification, then package artifacts, then add signing and notarization later."
  ].join("\n"),
  "../docs/UI_AND_UX_GUIDELINES.md": [
    "# UI and UX Guidelines",
    "",
    "## Product Direction",
    "",
    "Mac Control Center should feel like a polished macOS utility, not a web app transplanted into SwiftUI.",
    "",
    "## Design Principles",
    "",
    "### Native First",
    "",
    "- Prefer native controls and semantic macOS colors",
    "- Keep interactions lightweight and immediate",
    "- Let macOS window chrome do as much work as possible",
    "",
    "### Compact But Legible",
    "",
    "- Expanded view is for management",
    "- Mini view is for quick utility access",
    "- Dot view is for minimum screen footprint",
    "",
    "### Current UI Debt",
    "",
    "- Quick-launch dock is hardcoded rather than user-managed",
    "- Action feedback is heavier on notifications than inline clarity",
    "- There is no validation UI for conflicting shortcuts"
  ].join("\n"),
  "../BEHAVIORS.md": [
    "# Mac Control Center Behaviors",
    "",
    "This file is the fast-reference behavior log for the app.",
    "",
    "## View Modes",
    "",
    "### Expanded",
    "",
    "- Default working mode for the full action list",
    "- Shows toolbar controls, inline settings, add-action flow, edit mode, and the quick-launch dock",
    "",
    "### Mini",
    "",
    "- Condensed control mode for quick access to actions",
    "- Shows the view mode picker, always-on-top toggle, compact action list, and quick-launch dock",
    "",
    "### Dot",
    "",
    "- Minimal floating mode for reduced visual footprint",
    "- Returns to Mini mode on click",
    "",
    "## Shortcuts",
    "",
    "- `Ctrl + Cmd + L`: Expanded mode",
    "- `Ctrl + Cmd + M`: Mini mode",
    "- `Ctrl + Cmd + S`: Dot mode",
    "- `Ctrl + Cmd + T`: Toggle Always on Top",
    "- `Ctrl + Cmd + D`: Toggle Show on All Desktops",
    "- `Cmd + ,`: Toggle inline settings"
  ].join("\n"),
  "../SECURITY.md": [
    "# Security Policy",
    "",
    "## Public Repo Rules",
    "",
    "This repository is public. Do not commit secrets, private tokens, local credentials, personal URLs, or machine-specific data.",
    "",
    "## Development Guardrails",
    "",
    "1. Use `.env` files or OS-level secure storage for secrets.",
    "2. Keep local-only files out of git with `.gitignore`.",
    "3. Avoid hardcoded personal filesystem paths when a portable path will work.",
    "4. Treat exported task-tracker snapshots as reviewable content before sharing them online.",
    "5. Review shell-command examples carefully because the app can run user-defined shell actions."
  ].join("\n"),
  "../.agent/skills/always_rerun_app/SKILL.md": [
    "# Post-Change Verification",
    "",
    "Use this when changing Mac Control Center code and you need the standard rebuild and relaunch loop after meaningful edits.",
    "",
    "## Default Loop",
    "",
    "1. Close any running copy of `MacControlCenter` if needed.",
    "2. Run `./build.sh`.",
    "3. Launch with `open \"build/MacControlCenter.app\"` when interactive validation matters.",
    "4. Re-check git status so generated files are not accidentally staged."
  ].join("\n"),
  "../.agent/skills/build_and_run_app/SKILL.md": [
    "# Build and Run App",
    "",
    "Run these commands from the repo root.",
    "",
    "## Building the App",
    "",
    "```bash",
    "./build.sh",
    "```",
    "",
    "## Installing the App",
    "",
    "```bash",
    "./build.sh --install",
    "```",
    "",
    "## Running the App",
    "",
    "```bash",
    "open \"build/MacControlCenter.app\"",
    "```"
  ].join("\n"),
  "../.agent/skills/document_behaviors/SKILL.md": [
    "# Document Behaviors",
    "",
    "Update project docs in the same pass as behavior changes.",
    "",
    "## Minimum Update Set",
    "",
    "1. Update `BEHAVIORS.md` for interaction changes.",
    "2. Update the relevant file in `docs/` if architecture, persistence, or workflow changed.",
    "3. If the tracker or project workflow changed, also update `docs/LOCAL_PROJECT_SYSTEM.md`."
  ].join("\n"),
  "../.agent/skills/maintain_task_tracker/SKILL.md": [
    "# Maintain Task Tracker",
    "",
    "Use this skill when changing `TaskTracker/` or project-management docs.",
    "",
    "## Rules",
    "",
    "1. Keep repo-owned seed data in `TaskTracker/project-data.js`.",
    "2. Treat browser edits as local working state, not automatic repo updates.",
    "3. Mark AI-suggested backlog items with `source: recommended` and `recommendedBy: Codex (GPT-5)`.",
    "4. If docs structure changes, update both `TaskTracker/docs.html` and `docs/README.md`."
  ].join("\n"),
  "../.agent/skills/github_actions_ci/SKILL.md": [
    "# GitHub Actions CI",
    "",
    "Prefer small, verifiable steps.",
    "",
    "## Phase Order",
    "",
    "1. Add a macOS runner that executes `./build.sh`.",
    "2. Preserve build logs and artifacts.",
    "3. Only then add packaging, release uploads, signing, or notarization."
  ].join("\n"),
  "../.agent/skills/create_dmg_installer/SKILL.md": [
    "# Release Packaging Plan",
    "",
    "Use this checklist when moving from local builds to distributable artifacts.",
    "",
    "## Checklist",
    "",
    "1. Make sure `./build.sh` produces a stable app bundle.",
    "2. Decide whether the first release artifact is `.zip` or `.dmg`.",
    "3. Add a repeatable packaging script before publishing manually built artifacts.",
    "4. Update `docs/RELEASE_AND_DEPLOYMENT.md` when the packaging flow changes."
  ].join("\n"),
  "../.agent/skills/macos_native_ui_design/SKILL.md": [
    "# macOS Native UI Design Guidelines",
    "",
    "Mac Control Center should feel like a real macOS utility, not a generic cross-platform panel.",
    "",
    "## Principles",
    "",
    "- Prefer native controls, semantic colors, and macOS spacing.",
    "- Keep density appropriate to the mode.",
    "- Preserve immediate response for launch and run actions.",
    "- Add tooltips for icon-only controls."
  ].join("\n"),
  "../.agent/skills/top_notch_mac_ux/SKILL.md": [
    "# Mac Utility UX",
    "",
    "Menu bar utilities win on speed, clarity, and low friction.",
    "",
    "## Rules",
    "",
    "- Prefer instant actions over heavy confirmation flows.",
    "- Do not steal focus unnecessarily.",
    "- Preserve context when switching modes.",
    "- Make errors actionable, not generic."
  ].join("\n"),
  "../.agent/skills/prevent_secrets_leak/SKILL.md": [
    "# Protect Public Repo",
    "",
    "This repo is public. Review changes with that assumption.",
    "",
    "## Watch For",
    "",
    "- API keys, tokens, passwords, private URLs",
    "- exported local state that was not meant for sharing",
    "- user-specific filesystem paths",
    "- shell commands or docs that accidentally expose private workspace details"
  ].join("\n"),
  "PHASES.md": [
    "# LTM — Phase Build Plan",
    "",
    "> ⚠️ **Temporary documentation.** This file tracks the phased build plan for the LTM redesign.",
    "> Once all phases are complete and the app is stable, remove this entry from `project-data.js`",
    "> and delete `PHASES.md` from the repo.",
    "",
    "Each phase ends with a **commit + push**, then copy the prompt block for the next phase",
    "into a fresh Claude Code chat window. Every prompt is fully self-contained.",
    "",
    "---",
    "",
    "## ✅ Phase 0 — Full LTM Redesign (complete)",
    "",
    "**Commit:** `347345f` on `main`",
    "",
    "### What was built",
    "",
    "- **Header:** Abstract kanban SVG logo (3 bars: purple → teal → grey), LTM branding,",
    "  Tasks / Docs / Resources nav tabs. Subtitle moved behind the ⓘ icon.",
    "- **Toolbar:** Minimal bar — List View / Board View tab switcher, collapsible search + filter",
    "  bar triggered by icon buttons, + New button. Meta-row seed pills removed.",
    "- **List view:** Flat tabular layout. Hover reveals ✓ Done pill + edit on the right.",
    "  Clicking a row opens the Notion-style task detail panel.",
    "- **Board view:** Full-width, 6 columns (Newly Added or Updated · Backlog · Processing / On Hold",
    "  · In Progress · Completed · Archive). Columns collapse to vertical strips on the right",
    "  (Notion style). 3-dot column menu: rename, move left/right, hide, delete.",
    "  + New item footer per column. + Add column button at the end.",
    "- **Task detail panel:** Slides in from the right. Large editable title, properties grid",
    "  (stage, urgency, value, area, modified date), contenteditable rich-text notes editor",
    "  with Cmd+B / Cmd+I / Cmd+Shift+8 shortcuts and auto-bullet. Auto-saves to localStorage.",
    "  Designed as a drop-in for BlockNote in Phase 3.",
    "- **Resources tab:** `resources.html` static listing + `TaskTracker/resources/` folder.",
    "  Tracked in git, excluded from the macOS app build.",
    "- **Project context:** `CLAUDE.md` + `SKILL.md` added to `TaskTracker/` for Claude Code",
    "  context when opening this folder as a workspace.",
    "",
    "---",
    "",
    "## 🔲 Phase 1 — Bug fixes & polish",
    "",
    "**End-of-phase commit:**",
    "```",
    "git add -A && git commit -m \"fix(ltm): phase 1 — custom lanes, full-width board, inline stage select, list sort\"",
    "git push",
    "```",
    "",
    "### Copy-paste prompt for new chat window",
    "",
    "```",
    "Workspace: Open 0A. Mac Control Centre/TaskTracker/ in Claude Code.",
    "Read CLAUDE.md and SKILL.md before doing anything.",
    "",
    "Context: The LTM (Local Task Manager) was fully redesigned in the previous session",
    "(commit 347345f). It is a vanilla JS/HTML/CSS app — no build step.",
    "Open TaskTracker/index.html in the browser before starting.",
    "",
    "Fix these known issues one by one, testing in the browser after each:",
    "",
    "1. Custom columns + list view — When a column is added via the + button on the board,",
    "   its dropLane key (e.g. custom-1234567) is not in ACTIVE_LANES, so tasks moved into",
    "   it disappear from List View. Fix: in task-app.js → confirmAddColumn(), push the new",
    "   key into ACTIVE_LANES at runtime so it appears in list view.",
    "",
    "2. Board full-width — The board sits inside a max-width: 1400px .page-wrap. Extract",
    "   #boardView outside .page-wrap in index.html so when Board View is active the board",
    "   runs edge-to-edge. Toolbar and list view stay inside .page-wrap.",
    "   CSS hint: give #boardView padding: 0 24px 48px; width: 100%; when active.",
    "",
    "3. Detail panel — inline lane change — The Stage row in the detail panel properties",
    "   grid shows read-only text. Make it an inline <select> so the user can change stage",
    "   directly without opening the edit modal. On change → call moveTask() and re-render",
    "   props. See refreshDetailProps() in task-app.js.",
    "",
    "4. List view sort controls — Add a small sort bar above the task list:",
    "   Sort: Urgency · Value · Modified — text toggles, default urgency. Clicking re-sorts.",
    "   Store preference in localStorage ui.listSort.",
    "",
    "5. Visual QA — Check all 3 pages (Tasks, Docs, Resources) look correct: consistent",
    "   header, no broken links, board columns render at the right width.",
    "",
    "End by:",
    "- git add -A && git commit -m 'fix(ltm): phase 1 — custom lanes, full-width board, inline stage select, list sort'",
    "- git push",
    "- Open TaskTracker/PHASES.md and copy the Phase 2 prompt for the next window.",
    "```",
    "",
    "---",
    "",
    "## 🔲 Phase 2 — UX polish & missing fields",
    "",
    "**End-of-phase commit:**",
    "```",
    "git add -A && git commit -m \"feat(ltm): phase 2 — due date, keyboard shortcuts, value chip, drag handle\"",
    "git push",
    "```",
    "",
    "### Copy-paste prompt for new chat window",
    "",
    "```",
    "Workspace: Open 0A. Mac Control Centre/TaskTracker/ in Claude Code.",
    "Read CLAUDE.md and SKILL.md before doing anything.",
    "",
    "Context: The LTM (Local Task Manager) is a vanilla JS/HTML/CSS task tracker — no build step.",
    "Open TaskTracker/index.html in a browser first. Phase 1 bugs are already fixed.",
    "",
    "Add these features one by one, testing in the browser after each:",
    "",
    "1. Due date field — Add dueDate (ISO date string, optional) to normalizeTask() in task-app.js.",
    "   Add a date input to the create/edit modal form. Show it in the detail panel properties grid.",
    "   In list view, if dueDate is today or overdue, show a small coloured date badge next to",
    "   the task title.",
    "",
    "2. Keyboard shortcuts legend — Add a ? icon button to the toolbar (next to filter button).",
    "   Clicking it shows a compact popover listing:",
    "   N = new task · / = search · Esc = close · Cmd+B = bold · Cmd+I = italic",
    "   Style consistent with the col-menu popover in styles.css.",
    "",
    "3. Board card value chip — If task.value > 0, show a small $X,XXX chip at the bottom",
    "   of the board card. Subtle style — muted text, similar to .board-card-sublane.",
    "",
    "4. Drag handle on board cards — Add an explicit 6-dot drag handle (⠿) on the left of",
    "   each board card. Only the handle initiates drag. Rest of card click opens detail panel.",
    "   Update buildBoardCard() in task-app.js.",
    "",
    "5. Empty state copy — Update messages:",
    "   List view empty: 'No active tasks. Press N to add one.'",
    "   Board column empty: 'Drop a card here or click + New item'",
    "",
    "End by:",
    "- git add -A && git commit -m 'feat(ltm): phase 2 — due date, keyboard shortcuts, value chip, drag handle'",
    "- git push",
    "- Open TaskTracker/PHASES.md and copy the Phase 3 prompt for the next window.",
    "```",
    "",
    "---",
    "",
    "## 🔲 Phase 3 — BlockNote migration",
    "",
    "**End-of-phase commit:**",
    "```",
    "git add -A && git commit -m \"feat(ltm): phase 3 — BlockNote rich text editor\"",
    "git push",
    "```",
    "",
    "### Copy-paste prompt for new chat window",
    "",
    "```",
    "Workspace: Open 0A. Mac Control Centre/TaskTracker/ in Claude Code.",
    "Read CLAUDE.md and SKILL.md before doing anything.",
    "",
    "Context: The LTM notes editor currently uses a contenteditable div (task-app.js).",
    "It is designed to be replaced with BlockNote. The swap interface is",
    "getEditorContent() / setEditorContent() in task-app.js. task.body stores the content.",
    "",
    "BlockNote requires React. Add a Vite + React build to TaskTracker/editor/ as a",
    "mini app that bridges via postMessage:",
    "",
    "1. Scaffold: cd TaskTracker && npm create vite@latest editor -- --template react",
    "   cd editor && npm install @blocknote/core @blocknote/react @blocknote/mantine",
    "",
    "2. The editor app should:",
    "   - Receive content via window.addEventListener('message', ...) for type 'set'",
    "   - Send changes via window.parent.postMessage({ type: 'change', content }) on editor change",
    "   - Style BlockNote to match the dark theme (override BlockNote CSS variables to match",
    "     --bg: #0f1016, --text: #f8f9fa, --accent: #8b5cf6 from styles.css)",
    "",
    "3. In task-app.js replace #notesEditor div with an <iframe src='editor/dist/index.html'>",
    "   and update getEditorContent() / setEditorContent() to use postMessage.",
    "",
    "4. Storage: BlockNote content is a JSON block array. Update task.body to store this",
    "   JSON string. Update plainPreview() in task-app.js to extract text from block JSON",
    "   for list/board card previews.",
    "",
    "5. Build and commit: npm run build inside editor/. Commit editor/dist/.",
    "   Add editor/node_modules/ to root .gitignore.",
    "",
    "Test: create task → open detail → type rich content → close → reopen → content persists.",
    "",
    "End by:",
    "- git add -A && git commit -m 'feat(ltm): phase 3 — BlockNote rich text editor via iframe bridge'",
    "- git push",
    "- Open TaskTracker/PHASES.md and copy the Phase 4 prompt for the next window.",
    "```",
    "",
    "---",
    "",
    "## 🔲 Phase 4 — Portability & multi-project setup",
    "",
    "**End-of-phase commit:**",
    "```",
    "git add -A && git commit -m \"feat(ltm): phase 4 — ltm.config.json, setup.sh, README rewrite\"",
    "git push",
    "```",
    "",
    "### Copy-paste prompt for new chat window",
    "",
    "```",
    "Workspace: Open 0A. Mac Control Centre/TaskTracker/ in Claude Code.",
    "Read CLAUDE.md and SKILL.md before doing anything.",
    "",
    "Context: The LTM is designed to be dropped into any project repo. The project name,",
    "areas, and seed tasks are hardcoded in project-data.js. This phase makes it portable.",
    "",
    "1. ltm.config.json — Extract project identity from project-data.js into a new",
    "   TaskTracker/ltm.config.json:",
    "   { name, fullName, storageKey, areas, seedVersion }",
    "   Load this in project-data.js at startup (inline fetch or just reference it).",
    "",
    "2. setup.sh — Write TaskTracker/setup.sh that copies LTM into a target repo:",
    "   ./setup.sh /path/to/target-repo 'My Project Name'",
    "   It should: copy TaskTracker/, replace name in ltm.config.json, clear seed tasks",
    "   (leave a blank example), print next steps.",
    "",
    "3. README — Rewrite TaskTracker/README.md as the canonical 'how to use LTM' guide.",
    "   Sections: What is LTM · Running locally · Customising · Adding docs · Column",
    "   management · Notes on the build exclusion.",
    "",
    "4. Cleanup — Remove PHASES.md from project-data.js docs list and delete PHASES.md",
    "   from the repo (all phases complete).",
    "",
    "End by:",
    "- git add -A && git commit -m 'feat(ltm): phase 4 — ltm.config.json, setup.sh, README rewrite'",
    "- git push",
    "```",
    "",
    "---",
    "",
    "## Notes for all phases",
    "",
    "- **Workspace:** Open `TaskTracker/` as the workspace (or parent `0A. Mac Control Centre/`)",
    "- **No build step** until Phase 3 — open `index.html` directly in browser",
    "- **Test after every change** in the browser",
    "- **Commit format:** `type(ltm): phase N — description`",
    "- **`CLAUDE.md`** inside `TaskTracker/` bootstraps Claude Code context automatically"
  ].join("\n")
};
