window.MCCDocContent = {
  "../docs/README.md": [
    "# Documentation Index",
    "",
    "This folder is the project documentation home for Mac Control Center.",
    "",
    "## Core Docs",
    "",
    "- `PROJECT_OVERVIEW.md`: Product summary, repo layout, and current scope.",
    "- `PROJECT_AUDIT.md`: Current-state audit and recommended next steps.",
    "- `APP_ARCHITECTURE.md`: High-level code architecture and runtime flow.",
    "- `ACTION_SYSTEM.md`: How actions are modeled, persisted, and executed.",
    "- `PERSISTENCE_AND_STATE.md`: What data lives where and how it survives restarts.",
    "- `LOCAL_PROJECT_SYSTEM.md`: How the local tracker, docs hub, and online sync model should work.",
    "- `RELEASE_AND_DEPLOYMENT.md`: Current release process and future packaging/CI plan.",
    "- `UI_AND_UX_GUIDELINES.md`: Native macOS design and interaction rules for this app.",
    "",
    "## Root-Level Reference Files",
    "",
    "- `../README.md`: Quick start and repo-level overview.",
    "- `../BEHAVIORS.md`: User-visible behavior log.",
    "- `../SECURITY.md`: Public repo and secrets guidance.",
    "",
    "## Maintenance Rule",
    "",
    "When product behavior changes, update the architecture or behavior docs in the same pass. When project-management workflow changes, update `LOCAL_PROJECT_SYSTEM.md` and the TaskTracker pages together."
  ].join("\n"),
  "../docs/PROJECT_OVERVIEW.md": [
    "# Project Overview",
    "",
    "## What This App Is",
    "",
    "Mac Control Center is a native macOS utility that gives the user a compact control hub for launching apps, running shell commands, and switching between multiple window modes.",
    "",
    "## Current Capabilities",
    "",
    "- Menu bar status item with a quick access menu",
    "- Main Dock window for managing actions",
    "- Expanded, Mini, and Dot display modes",
    "- Inline settings and inline action creation",
    "- Editable action list with reorder support",
    "- Local persistence for action configuration and window preferences",
    "- Quick-launch dock for a few frequently used apps",
    "",
    "## Repo Layout",
    "",
    "- `Sources/MacControlCenter/`: Swift source",
    "- `Resources/`: app icon and bundle assets",
    "- `build.sh`: local build and optional install script",
    "- `TaskTracker/`: local-first task tracker and documentation hub",
    "- `docs/`: markdown documentation for product, architecture, persistence, release, and workflow",
    "- `BEHAVIORS.md`: compact behavior log for user-visible interactions",
    "",
    "## Current Constraints",
    "",
    "- No automated tests yet",
    "- No packaged release workflow yet",
    "- No GitHub Actions CI/CD yet",
    "- Launch-at-login currently uses AppleScript login items",
    "- TaskTracker is local-first and browser-persistent, not automatically synced online"
  ].join("\n"),
  "../docs/PROJECT_AUDIT.md": [
    "# Project Audit",
    "",
    "Audit date: 2026-03-30",
    "",
    "## Current Strengths",
    "",
    "- The app is already native, lightweight, and buildable with a single script.",
    "- Configuration is separated from code through `ConfigManager`.",
    "- Action execution is isolated in `ActivityHandler`.",
    "- The window system already supports multiple usage modes with clear keyboard shortcuts.",
    "- The repository now has a local-first documentation and task-tracking structure.",
    "",
    "## Gaps Worth Addressing Next",
    "",
    "### Product",
    "",
    "- Quick-launch dock entries are hardcoded instead of user-configurable.",
    "- Action shortcut conflicts are not validated.",
    "- Action failures rely mostly on notifications rather than richer in-app feedback.",
    "- Import/export and backup for action config are not exposed in the UI.",
    "",
    "### Platform / Reliability",
    "",
    "- There is no automated build verification or test coverage.",
    "- Launch-at-login relies on AppleScript and may be brittle across macOS changes.",
    "- Shell action execution has limited safety guidance and no trust model.",
    "",
    "### Release / Operations",
    "",
    "- There is no GitHub Actions pipeline for build, package, or release.",
    "- There is no `.dmg` or `.zip` release artifact flow yet.",
    "- The local tracker does not automatically sync to any online system."
  ].join("\n"),
  "../docs/APP_ARCHITECTURE.md": [
    "# App Architecture",
    "",
    "## Runtime Entry Point",
    "",
    "`Sources/MacControlCenter/main.swift` starts the app, creates the status-item menu, opens the main window, and keeps the menu synchronized with configuration changes.",
    "",
    "## Main Components",
    "",
    "### `AppDelegate`",
    "",
    "- Creates the menu bar status item",
    "- Builds the status menu from saved actions",
    "- Opens and restores the main window",
    "- Rebuilds the menu when configuration changes",
    "",
    "### `ConfigManager`",
    "",
    "- Owns the action list",
    "- Loads and saves `config.json`",
    "- Normalizes action data before persistence",
    "- Publishes change notifications so the UI and menu stay in sync",
    "",
    "### `ActivityHandler`",
    "",
    "- Receives an `ActionButton`",
    "- Validates `actionType` and `actionTarget`",
    "- Launches applications with `NSWorkspace` or shell commands with `/bin/sh -c`",
    "- Shows notifications on invalid or failed actions"
  ].join("\n"),
  "../docs/ACTION_SYSTEM.md": [
    "# Action System",
    "",
    "## Data Model",
    "",
    "Each action is represented by `ActionButton`:",
    "",
    "- `id`: UUID generated locally",
    "- `name`: visible label",
    "- `key`: single-character shortcut",
    "- `actionType`: `app`, `shell`, or empty",
    "- `actionTarget`: application path or shell command",
    "",
    "## Storage Location",
    "",
    "`~/Library/Application Support/MacControlCenter/config.json`",
    "",
    "## Execution Rules",
    "",
    "- `app`: expects a valid `.app` path and launches with `NSWorkspace`",
    "- `shell`: runs through `/bin/sh -c`",
    "- empty or invalid action definitions trigger a user notification instead of a hard failure",
    "",
    "## Current Risks",
    "",
    "- Duplicate shortcuts are not prevented",
    "- There is no import/export UI for action backup",
    "- Shell commands can be powerful and should be treated as trusted local workflows",
    "- There is no richer execution log beyond notifications"
  ].join("\n"),
  "../docs/PERSISTENCE_AND_STATE.md": [
    "# Persistence and State",
    "",
    "This project has three different persistence layers, and they behave differently.",
    "",
    "## 1. App Configuration",
    "",
    "- Stored in `~/Library/Application Support/MacControlCenter/config.json`",
    "- Contains actions, keys, action types, and action targets",
    "- Local to the current macOS user account",
    "",
    "## 2. App Preferences",
    "",
    "- Stored in macOS `UserDefaults`",
    "- Contains view mode, always-on-top state, show-on-all-desktops state, opacity, and launch-at-login preference",
    "- Local to the current machine/user",
    "",
    "## 3. Local Task Tracker State",
    "",
    "- Repo seed data in `TaskTracker/project-data.js`",
    "- Browser-local working state in `localStorage`",
    "- Browser edits do not update the repo automatically",
    "- Browser edits do not update an online tracker automatically",
    "",
    "## Practical Answer",
    "",
    "If you add a new item in the local tracker UI, it will persist in that browser on that machine, but it will not automatically update across the board."
  ].join("\n"),
  "../docs/LOCAL_PROJECT_SYSTEM.md": [
    "# Local Project System",
    "",
    "## Goal",
    "",
    "Keep project management and documentation close to the codebase so AI agents and humans can update them in the same workspace.",
    "",
    "## Components",
    "",
    "### `TaskTracker/index.html`",
    "",
    "Local-first task board for backlog review, quick edits, export, and manual prioritization.",
    "",
    "### `TaskTracker/docs.html`",
    "",
    "Project docs hub linking the markdown docs and the repo-local skill files.",
    "",
    "### `TaskTracker/project-data.js`",
    "",
    "Repo-owned seed data for project metadata, seeded backlog items, docs index, and skill index.",
    "",
    "## AI-Recommended Tasks",
    "",
    "When an AI assistant adds a suggested task to the repo-owned backlog, mark it with `source: recommended` and `recommendedBy: Codex (GPT-5)`."
  ].join("\n"),
  "../docs/RELEASE_AND_DEPLOYMENT.md": [
    "# Release and Deployment",
    "",
    "## Current State",
    "",
    "The project supports local builds with `build.sh`.",
    "",
    "Current release process:",
    "",
    "1. Run `./build.sh`",
    "2. Open `build/MacControlCenter.app`",
    "3. Optionally install with `./build.sh --install`",
    "",
    "## What Does Not Exist Yet",
    "",
    "- GitHub Actions build pipeline",
    "- packaged `.dmg` or `.zip`",
    "- automated versioning",
    "- notarization / formal signing flow",
    "- GitHub Release publishing",
    "",
    "## Recommended Release Plan",
    "",
    "Start with build verification, then package artifacts, then add signing and notarization later."
  ].join("\n"),
  "../docs/UI_AND_UX_GUIDELINES.md": [
    "# UI and UX Guidelines",
    "",
    "## Product Direction",
    "",
    "Mac Control Center should feel like a polished macOS utility, not a web app transplanted into SwiftUI.",
    "",
    "## Design Principles",
    "",
    "### Native First",
    "",
    "- Prefer native controls and semantic macOS colors",
    "- Keep interactions lightweight and immediate",
    "- Let macOS window chrome do as much work as possible",
    "",
    "### Compact But Legible",
    "",
    "- Expanded view is for management",
    "- Mini view is for quick utility access",
    "- Dot view is for minimum screen footprint",
    "",
    "### Current UI Debt",
    "",
    "- Quick-launch dock is hardcoded rather than user-managed",
    "- Action feedback is heavier on notifications than inline clarity",
    "- There is no validation UI for conflicting shortcuts"
  ].join("\n"),
  "../BEHAVIORS.md": [
    "# Mac Control Center Behaviors",
    "",
    "This file is the fast-reference behavior log for the app.",
    "",
    "## View Modes",
    "",
    "### Expanded",
    "",
    "- Default working mode for the full action list",
    "- Shows toolbar controls, inline settings, add-action flow, edit mode, and the quick-launch dock",
    "",
    "### Mini",
    "",
    "- Condensed control mode for quick access to actions",
    "- Shows the view mode picker, always-on-top toggle, compact action list, and quick-launch dock",
    "",
    "### Dot",
    "",
    "- Minimal floating mode for reduced visual footprint",
    "- Returns to Mini mode on click",
    "",
    "## Shortcuts",
    "",
    "- `Ctrl + Cmd + L`: Expanded mode",
    "- `Ctrl + Cmd + M`: Mini mode",
    "- `Ctrl + Cmd + S`: Dot mode",
    "- `Ctrl + Cmd + T`: Toggle Always on Top",
    "- `Ctrl + Cmd + D`: Toggle Show on All Desktops",
    "- `Cmd + ,`: Toggle inline settings"
  ].join("\n"),
  "../SECURITY.md": [
    "# Security Policy",
    "",
    "## Public Repo Rules",
    "",
    "This repository is public. Do not commit secrets, private tokens, local credentials, personal URLs, or machine-specific data.",
    "",
    "## Development Guardrails",
    "",
    "1. Use `.env` files or OS-level secure storage for secrets.",
    "2. Keep local-only files out of git with `.gitignore`.",
    "3. Avoid hardcoded personal filesystem paths when a portable path will work.",
    "4. Treat exported task-tracker snapshots as reviewable content before sharing them online.",
    "5. Review shell-command examples carefully because the app can run user-defined shell actions."
  ].join("\n"),
  "../.agent/skills/always_rerun_app/SKILL.md": [
    "# Post-Change Verification",
    "",
    "Use this when changing Mac Control Center code and you need the standard rebuild and relaunch loop after meaningful edits.",
    "",
    "## Default Loop",
    "",
    "1. Close any running copy of `MacControlCenter` if needed.",
    "2. Run `./build.sh`.",
    "3. Launch with `open \"build/MacControlCenter.app\"` when interactive validation matters.",
    "4. Re-check git status so generated files are not accidentally staged."
  ].join("\n"),
  "../.agent/skills/build_and_run_app/SKILL.md": [
    "# Build and Run App",
    "",
    "Run these commands from the repo root.",
    "",
    "## Building the App",
    "",
    "```bash",
    "./build.sh",
    "```",
    "",
    "## Installing the App",
    "",
    "```bash",
    "./build.sh --install",
    "```",
    "",
    "## Running the App",
    "",
    "```bash",
    "open \"build/MacControlCenter.app\"",
    "```"
  ].join("\n"),
  "../.agent/skills/document_behaviors/SKILL.md": [
    "# Document Behaviors",
    "",
    "Update project docs in the same pass as behavior changes.",
    "",
    "## Minimum Update Set",
    "",
    "1. Update `BEHAVIORS.md` for interaction changes.",
    "2. Update the relevant file in `docs/` if architecture, persistence, or workflow changed.",
    "3. If the tracker or project workflow changed, also update `docs/LOCAL_PROJECT_SYSTEM.md`."
  ].join("\n"),
  "../.agent/skills/maintain_task_tracker/SKILL.md": [
    "# Maintain Task Tracker",
    "",
    "Use this skill when changing `TaskTracker/` or project-management docs.",
    "",
    "## Rules",
    "",
    "1. Keep repo-owned seed data in `TaskTracker/project-data.js`.",
    "2. Treat browser edits as local working state, not automatic repo updates.",
    "3. Mark AI-suggested backlog items with `source: recommended` and `recommendedBy: Codex (GPT-5)`.",
    "4. If docs structure changes, update both `TaskTracker/docs.html` and `docs/README.md`."
  ].join("\n"),
  "../.agent/skills/github_actions_ci/SKILL.md": [
    "# GitHub Actions CI",
    "",
    "Prefer small, verifiable steps.",
    "",
    "## Phase Order",
    "",
    "1. Add a macOS runner that executes `./build.sh`.",
    "2. Preserve build logs and artifacts.",
    "3. Only then add packaging, release uploads, signing, or notarization."
  ].join("\n"),
  "../.agent/skills/create_dmg_installer/SKILL.md": [
    "# Release Packaging Plan",
    "",
    "Use this checklist when moving from local builds to distributable artifacts.",
    "",
    "## Checklist",
    "",
    "1. Make sure `./build.sh` produces a stable app bundle.",
    "2. Decide whether the first release artifact is `.zip` or `.dmg`.",
    "3. Add a repeatable packaging script before publishing manually built artifacts.",
    "4. Update `docs/RELEASE_AND_DEPLOYMENT.md` when the packaging flow changes."
  ].join("\n"),
  "../.agent/skills/macos_native_ui_design/SKILL.md": [
    "# macOS Native UI Design Guidelines",
    "",
    "Mac Control Center should feel like a real macOS utility, not a generic cross-platform panel.",
    "",
    "## Principles",
    "",
    "- Prefer native controls, semantic colors, and macOS spacing.",
    "- Keep density appropriate to the mode.",
    "- Preserve immediate response for launch and run actions.",
    "- Add tooltips for icon-only controls."
  ].join("\n"),
  "../.agent/skills/top_notch_mac_ux/SKILL.md": [
    "# Mac Utility UX",
    "",
    "Menu bar utilities win on speed, clarity, and low friction.",
    "",
    "## Rules",
    "",
    "- Prefer instant actions over heavy confirmation flows.",
    "- Do not steal focus unnecessarily.",
    "- Preserve context when switching modes.",
    "- Make errors actionable, not generic."
  ].join("\n"),
  "../.agent/skills/prevent_secrets_leak/SKILL.md": [
    "# Protect Public Repo",
    "",
    "This repo is public. Review changes with that assumption.",
    "",
    "## Watch For",
    "",
    "- API keys, tokens, passwords, private URLs",
    "- exported local state that was not meant for sharing",
    "- user-specific filesystem paths",
    "- shell commands or docs that accidentally expose private workspace details"
  ].join("\n")
};
